spring.application.name=AegisTrace

server.port=8084

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/aegistrace_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Actuator
management.endpoints.web.exposure.include=*

# Security Login
spring.security.user.name=admin
spring.security.user.password=admin123

spring.jpa.open-in-view=false