spring.application.name=AegisTrace

server.port=8084

# MySQL Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/aegistrace_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Root@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Actuator
management.endpoints.web.exposure.include=${ACTUATOR_ENDPOINTS:health,info}

# Security Login
spring.security.user.name=admin
spring.security.user.password=admin123

spring.jpa.open-in-view=false

aegistrace.scanner.nmap.enabled=${NMAP_ENABLED:true}
